# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modern_progress_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 240)
        Form.setMinimumSize(QtCore.QSize(240, 240))
        Form.setMaximumSize(QtCore.QSize(240, 240))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.circularProgressBar_Main = QtWidgets.QFrame(self.frame)
        self.circularProgressBar_Main.setStyleSheet("background-color: none;")
        self.circularProgressBar_Main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBar_Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBar_Main.setObjectName("circularProgressBar_Main")
        self.circularProgress_5 = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularProgress_5.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularProgress_5.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.400 rgba(85, 170, 255, 255), stop:0.395 rgba(255, 255, 255, 0));\n"
"}")
        self.circularProgress_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularProgress_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgress_5.setObjectName("circularProgress_5")
        self.circularBg_5 = QtWidgets.QFrame(self.circularProgressBar_Main)
        self.circularBg_5.setGeometry(QtCore.QRect(10, 10, 220, 220))
        self.circularBg_5.setStyleSheet("QFrame{\n"
"    border-radius: 110px;    \n"
"    background-color: rgba(85, 85, 127, 100);\n"
"}")
        self.circularBg_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularBg_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg_5.setObjectName("circularBg_5")
        self.circularContainer_4 = QtWidgets.QFrame(self.circularBg_5)
        self.circularContainer_4.setGeometry(QtCore.QRect(6, 5, 210, 210))
        self.circularContainer_4.setMinimumSize(QtCore.QSize(210, 210))
        self.circularContainer_4.setBaseSize(QtCore.QSize(0, 0))
        self.circularContainer_4.setStyleSheet("QFrame{\n"
"    border-radius: 105px;    \n"
"    background-color: rgb(33, 37, 43);\n"
"}")
        self.circularContainer_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circularContainer_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularContainer_4.setObjectName("circularContainer_4")
        self.layoutWidget_5 = QtWidgets.QWidget(self.circularContainer_4)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 40, 191, 154))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.infoLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.infoLayout_4.setContentsMargins(0, 0, 0, 0)
        self.infoLayout_4.setObjectName("infoLayout_4")
        self.labelHeader = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.labelHeader.setFont(font)
        self.labelHeader.setStyleSheet("color: rgb(115, 185, 255); background-color: none;")
        self.labelHeader.setText("")
        self.labelHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHeader.setObjectName("labelHeader")
        self.infoLayout_4.addWidget(self.labelHeader, 0, 0, 1, 1)
        self.labelFooter = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.labelFooter.setFont(font)
        self.labelFooter.setStyleSheet("color: rgb(148, 148, 216); background-color: none;")
        self.labelFooter.setText("")
        self.labelFooter.setAlignment(QtCore.Qt.AlignCenter)
        self.labelFooter.setObjectName("labelFooter")
        self.infoLayout_4.addWidget(self.labelFooter, 2, 0, 1, 1)
        self.labelPercen = QtWidgets.QLabel(self.layoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("72 Light")
        font.setPointSize(10)
        self.labelPercen.setFont(font)
        self.labelPercen.setStyleSheet("color: rgb(115, 185, 255); padding: 0px; background-color: none;")
        self.labelPercen.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPercen.setIndent(-1)
        self.labelPercen.setObjectName("labelPercen")
        self.infoLayout_4.addWidget(self.labelPercen, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.circularProgressBar_Main)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelPercen.setText(_translate("Form", "<p align=\"center\"><span style=\" font-size:50pt;\">60</span><span style=\" font-size:40pt; vertical-align:super;\">%</span></p>"))
