# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\my-py-projects\R4Editor\ui\form_recent_projects.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(583, 359)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("QWidget, QFrame, QPushButton, QLineEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(200, 200, 200);\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton {    \n"
"    border: none;\n"
"    padding: 7 17;\n"
"    width: 50px;\n"
"    background-color: rgb(39, 44, 54);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    color: rgb(100, 100, 100);\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_logo_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_logo_2.sizePolicy().hasHeightForWidth())
        self.frame_logo_2.setSizePolicy(sizePolicy)
        self.frame_logo_2.setStyleSheet("/*background: transparent;\n"
"background-image: url(:/16x16/icons/16x16/cil-terminal.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;*/")
        self.frame_logo_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo_2.setObjectName("frame_logo_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_logo_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.frame_logo_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("ZF Serif")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(58, 89, 245);")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        self.label_title_bar_top = QtWidgets.QLabel(self.frame_logo_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_title_bar_top.sizePolicy().hasHeightForWidth())
        self.label_title_bar_top.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_title_bar_top.setFont(font)
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"color: rgb(180, 180, 180);\n"
"padding-bottom: 8px;\n"
"margin-left: -10px;\n"
"min-width: 10px;\n"
"")
        self.label_title_bar_top.setIndent(0)
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_9.addWidget(self.label_title_bar_top, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.frame_logo_2, 0, QtCore.Qt.AlignHCenter)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ui_lw_projects = QtWidgets.QListWidget(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lw_projects.setFont(font)
        self.ui_lw_projects.setStyleSheet("QListWidget::item{\n"
"    color: rgb(200,200,200);\n"
"    padding: 10px;\n"
"}\n"
"")
        self.ui_lw_projects.setIconSize(QtCore.QSize(25, 25))
        self.ui_lw_projects.setViewMode(QtWidgets.QListView.ListMode)
        self.ui_lw_projects.setObjectName("ui_lw_projects")
        self.horizontalLayout_3.addWidget(self.ui_lw_projects)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_top = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 0))
        self.frame_top.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QFrame:{\n"
"padding: 5px;\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_logo = QtWidgets.QFrame(self.frame_top)
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_logo)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.logo = QtWidgets.QLabel(self.frame_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("ZF Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgb(58, 89, 245);")
        self.logo.setObjectName("logo")
        self.horizontalLayout_6.addWidget(self.logo)
        self.horizontalLayout_4.addWidget(self.frame_logo)
        self.frame_caption = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_caption.sizePolicy().hasHeightForWidth())
        self.frame_caption.setSizePolicy(sizePolicy)
        self.frame_caption.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_caption.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_caption.setObjectName("frame_caption")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_caption)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_window_name = QtWidgets.QLabel(self.frame_caption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_window_name.sizePolicy().hasHeightForWidth())
        self.label_window_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_window_name.setFont(font)
        self.label_window_name.setText("")
        self.label_window_name.setObjectName("label_window_name")
        self.horizontalLayout_5.addWidget(self.label_window_name)
        self.horizontalLayout_4.addWidget(self.frame_caption)
        self.frame_close = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_close.sizePolicy().hasHeightForWidth())
        self.frame_close.setSizePolicy(sizePolicy)
        self.frame_close.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_close = QtWidgets.QPushButton(self.frame_close)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_close.setStyleSheet("")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_7.addWidget(self.btn_close)
        self.horizontalLayout_4.addWidget(self.frame_close, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_top)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_21 = QtWidgets.QFrame(self.frame_17)
        self.frame_21.setStyleSheet("")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_bottom_buttons = QtWidgets.QFrame(self.frame_21)
        self.frame_bottom_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom_buttons.setObjectName("frame_bottom_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_bottom_buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ui_btn_ok = QtWidgets.QPushButton(self.frame_bottom_buttons)
        self.ui_btn_ok.setEnabled(False)
        self.ui_btn_ok.setObjectName("ui_btn_ok")
        self.horizontalLayout.addWidget(self.ui_btn_ok)
        self.ui_btn_open = QtWidgets.QPushButton(self.frame_bottom_buttons)
        self.ui_btn_open.setObjectName("ui_btn_open")
        self.horizontalLayout.addWidget(self.ui_btn_open)
        self.ui_btn_remove = QtWidgets.QPushButton(self.frame_bottom_buttons)
        self.ui_btn_remove.setEnabled(False)
        self.ui_btn_remove.setObjectName("ui_btn_remove")
        self.horizontalLayout.addWidget(self.ui_btn_remove)
        self.horizontalLayout_2.addWidget(self.frame_bottom_buttons)
        self.horizontalLayout_20.addWidget(self.frame_21, 0, QtCore.Qt.AlignLeft)
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setEnabled(True)
        self.frame_23.setStyleSheet("")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_23.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ui_btn_close = QtWidgets.QPushButton(self.frame_23)
        self.ui_btn_close.setObjectName("ui_btn_close")
        self.horizontalLayout_23.addWidget(self.ui_btn_close)
        self.horizontalLayout_20.addWidget(self.frame_23, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_24.addWidget(self.frame_17)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "R2"))
        self.label_title_bar_top.setText(_translate("Form", "EDITOR"))
        self.logo.setText(_translate("Form", "R2"))
        self.btn_close.setToolTip(_translate("Form", "Close"))
        self.ui_btn_ok.setText(_translate("Form", "OK"))
        self.ui_btn_open.setText(_translate("Form", "Open..."))
        self.ui_btn_remove.setText(_translate("Form", "Remove"))
        self.ui_btn_close.setText(_translate("Form", "Cancel"))
import files_rc
