# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\my-py-projects\R4Editor\ui\model_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2262, 1020)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_17 = QtWidgets.QFrame(self.frame)
        self.frame_17.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    padding: 15;\n"
"    /*border-right: 5px solid rgb(44, 49, 60);*/\n"
"    background-color: rgb(39, 44, 54);\n"
"    text-align: left;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"    padding: 5;\n"
"}\n"
"\n"
"QFrame{\n"
"background-color: rgb(39, 44, 54);\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.frame_21 = QtWidgets.QFrame(self.frame_17)
        self.frame_21.setStyleSheet("")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_21.setContentsMargins(5, 0, -1, 0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_22 = QtWidgets.QFrame(self.frame_21)
        self.frame_22.setStyleSheet("QLineEdit{\n"
"    padding-left: 30px;\n"
"    border-radius: 1px;\n"
"}")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uiBtnEditNode = QtWidgets.QPushButton(self.frame_22)
        self.uiBtnEditNode.setEnabled(True)
        self.uiBtnEditNode.setMaximumSize(QtCore.QSize(0, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBtnEditNode.setIcon(icon)
        self.uiBtnEditNode.setCheckable(False)
        self.uiBtnEditNode.setObjectName("uiBtnEditNode")
        self.horizontalLayout_2.addWidget(self.uiBtnEditNode)
        self.horizontalLayout_21.addWidget(self.frame_22)
        self.horizontalLayout_20.addWidget(self.frame_21, 0, QtCore.Qt.AlignLeft)
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setEnabled(True)
        self.frame_23.setStyleSheet("")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.uiBtnCheckCoverage = QtWidgets.QPushButton(self.frame_23)
        self.uiBtnCheckCoverage.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-task.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBtnCheckCoverage.setIcon(icon1)
        self.uiBtnCheckCoverage.setObjectName("uiBtnCheckCoverage")
        self.horizontalLayout_23.addWidget(self.uiBtnCheckCoverage)
        self.uiBtnCheckHtmlReport = QtWidgets.QPushButton(self.frame_23)
        self.uiBtnCheckHtmlReport.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-notes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBtnCheckHtmlReport.setIcon(icon2)
        self.uiBtnCheckHtmlReport.setObjectName("uiBtnCheckHtmlReport")
        self.horizontalLayout_23.addWidget(self.uiBtnCheckHtmlReport)
        self.uiBtnUpdateRequirements = QtWidgets.QPushButton(self.frame_23)
        self.uiBtnUpdateRequirements.setEnabled(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-cloud-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBtnUpdateRequirements.setIcon(icon3)
        self.uiBtnUpdateRequirements.setObjectName("uiBtnUpdateRequirements")
        self.horizontalLayout_23.addWidget(self.uiBtnUpdateRequirements)
        self.uiBtnNewModule = QtWidgets.QPushButton(self.frame_23)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/20x20/icons/20x20/cil-plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBtnNewModule.setIcon(icon4)
        self.uiBtnNewModule.setObjectName("uiBtnNewModule")
        self.horizontalLayout_23.addWidget(self.uiBtnNewModule)
        self.horizontalLayout_20.addWidget(self.frame_23, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_24.addWidget(self.frame_17)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_2.setStyleSheet("background-color: rgb(33, 37, 43);\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_12.setContentsMargins(-1, 5, -1, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lab_requirements = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_requirements.sizePolicy().hasHeightForWidth())
        self.lab_requirements.setSizePolicy(sizePolicy)
        self.lab_requirements.setMaximumSize(QtCore.QSize(16777215, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lab_requirements.setFont(font)
        self.lab_requirements.setStyleSheet("color: rgb(150, 150, 150);")
        self.lab_requirements.setObjectName("lab_requirements")
        self.verticalLayout_12.addWidget(self.lab_requirements, 0, QtCore.Qt.AlignHCenter)
        self.frame_34 = QtWidgets.QFrame(self.frame_2)
        self.frame_34.setStyleSheet("QFrame{\n"
"    background-color: rgb(33, 37, 43);\n"
"}")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_32.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_32.setSpacing(15)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frame_33 = QtWidgets.QFrame(self.frame_34)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_33.sizePolicy().hasHeightForWidth())
        self.frame_33.setSizePolicy(sizePolicy)
        self.frame_33.setStyleSheet("color: rgb(150, 150, 150);\n"
"\n"
"")
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_11.setContentsMargins(-1, -1, 15, -1)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_35 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_35.sizePolicy().hasHeightForWidth())
        self.frame_35.setSizePolicy(sizePolicy)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.icon_2 = QtWidgets.QLabel(self.frame_35)
        self.icon_2.setText("")
        self.icon_2.setPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-folder.png"))
        self.icon_2.setObjectName("icon_2")
        self.horizontalLayout_33.addWidget(self.icon_2)
        self.name_2 = QtWidgets.QLabel(self.frame_35)
        self.name_2.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_2.setFont(font)
        self.name_2.setObjectName("name_2")
        self.horizontalLayout_33.addWidget(self.name_2)
        self.ui_lab_project_path = QtWidgets.QLabel(self.frame_35)
        self.ui_lab_project_path.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ui_lab_project_path.setFont(font)
        self.ui_lab_project_path.setStyleSheet("color: rgb(200,200,200);")
        self.ui_lab_project_path.setObjectName("ui_lab_project_path")
        self.horizontalLayout_33.addWidget(self.ui_lab_project_path)
        self.uiBtnSetProjectPath = QtWidgets.QPushButton(self.frame_35)
        self.uiBtnSetProjectPath.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uiBtnSetProjectPath.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    padding: 5;\n"
"    /*border-right: 5px solid rgb(44, 49, 60);*/\n"
"    background-color: rgb(58, 89, 245);\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QPushButton:disabled {    \n"
"    color: rgb(80, 80, 80);\n"
"\n"
"}")
        self.uiBtnSetProjectPath.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-options-horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uiBtnSetProjectPath.setIcon(icon5)
        self.uiBtnSetProjectPath.setObjectName("uiBtnSetProjectPath")
        self.horizontalLayout_33.addWidget(self.uiBtnSetProjectPath)
        self.verticalLayout_11.addWidget(self.frame_35, 0, QtCore.Qt.AlignLeft)
        self.frame_38 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_38.sizePolicy().hasHeightForWidth())
        self.frame_38.setSizePolicy(sizePolicy)
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout(self.frame_38)
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.icon_5 = QtWidgets.QLabel(self.frame_38)
        self.icon_5.setText("")
        self.icon_5.setPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-library.png"))
        self.icon_5.setObjectName("icon_5")
        self.horizontalLayout_36.addWidget(self.icon_5)
        self.name_5 = QtWidgets.QLabel(self.frame_38)
        self.name_5.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_5.setFont(font)
        self.name_5.setObjectName("name_5")
        self.horizontalLayout_36.addWidget(self.name_5)
        self.ui_lab_req_total = QtWidgets.QLabel(self.frame_38)
        self.ui_lab_req_total.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_lab_req_total.setFont(font)
        self.ui_lab_req_total.setStyleSheet("color: rgb(200,200,200);")
        self.ui_lab_req_total.setObjectName("ui_lab_req_total")
        self.horizontalLayout_36.addWidget(self.ui_lab_req_total)
        self.verticalLayout_11.addWidget(self.frame_38, 0, QtCore.Qt.AlignLeft)
        self.frame_37 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_37.sizePolicy().hasHeightForWidth())
        self.frame_37.setSizePolicy(sizePolicy)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.frame_37)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.icon_4 = QtWidgets.QLabel(self.frame_37)
        self.icon_4.setText("")
        self.icon_4.setPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-check-circle.png"))
        self.icon_4.setObjectName("icon_4")
        self.horizontalLayout_35.addWidget(self.icon_4)
        self.name_4 = QtWidgets.QLabel(self.frame_37)
        self.name_4.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_4.setFont(font)
        self.name_4.setObjectName("name_4")
        self.horizontalLayout_35.addWidget(self.name_4)
        self.ui_lab_req_covered = QtWidgets.QLabel(self.frame_37)
        self.ui_lab_req_covered.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_lab_req_covered.setFont(font)
        self.ui_lab_req_covered.setStyleSheet("color: rgb(50,200,50);")
        self.ui_lab_req_covered.setObjectName("ui_lab_req_covered")
        self.horizontalLayout_35.addWidget(self.ui_lab_req_covered)
        self.verticalLayout_11.addWidget(self.frame_37, 0, QtCore.Qt.AlignLeft)
        self.frame_36 = QtWidgets.QFrame(self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_36.sizePolicy().hasHeightForWidth())
        self.frame_36.setSizePolicy(sizePolicy)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_36)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.icon_3 = QtWidgets.QLabel(self.frame_36)
        self.icon_3.setText("")
        self.icon_3.setPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x-circle.png"))
        self.icon_3.setObjectName("icon_3")
        self.horizontalLayout_34.addWidget(self.icon_3)
        self.name_3 = QtWidgets.QLabel(self.frame_36)
        self.name_3.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_3.setFont(font)
        self.name_3.setObjectName("name_3")
        self.horizontalLayout_34.addWidget(self.name_3)
        self.ui_lab_req_not_covered = QtWidgets.QLabel(self.frame_36)
        self.ui_lab_req_not_covered.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ui_lab_req_not_covered.setFont(font)
        self.ui_lab_req_not_covered.setStyleSheet("color: rgb(200,50,50);")
        self.ui_lab_req_not_covered.setObjectName("ui_lab_req_not_covered")
        self.horizontalLayout_34.addWidget(self.ui_lab_req_not_covered)
        self.verticalLayout_11.addWidget(self.frame_36, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_32.addWidget(self.frame_33, 0, QtCore.Qt.AlignVCenter)
        self.ui_layout_data_summary = QtWidgets.QHBoxLayout()
        self.ui_layout_data_summary.setObjectName("ui_layout_data_summary")
        self.horizontalLayout_32.addLayout(self.ui_layout_data_summary)
        self.verticalLayout_12.addWidget(self.frame_34, 0, QtCore.Qt.AlignHCenter)
        self.lab_project_files = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_project_files.sizePolicy().hasHeightForWidth())
        self.lab_project_files.setSizePolicy(sizePolicy)
        self.lab_project_files.setMaximumSize(QtCore.QSize(16777215, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lab_project_files.setFont(font)
        self.lab_project_files.setStyleSheet("color: rgb(150, 150, 150);")
        self.lab_project_files.setObjectName("lab_project_files")
        self.verticalLayout_12.addWidget(self.lab_project_files, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setStyleSheet("QFrame, QLineEdit{\n"
"    background-color: rgb(33, 37, 43);\n"
"\n"
"    font-family: \"Arial Narrow\", Arial, \"Helvetica Condensed\", Helvetica, sans-serif;\n"
"\n"
"    font-size: 14px;\n"
"\n"
"    letter-spacing: 1.3px;\n"
"}\n"
"\n"
"QWidget{\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QLabel{\n"
"color: rgb(95, 180, 255);\n"
"color: rgb(150, 150, 150);\n"
"font-weight: bold;\n"
"min-width: 80px;\n"
"}\n"
"\n"
"QListWidget, QTextEdit{\n"
"    border: 1px solid rgb(50,50,50);\n"
"}\n"
"\n"
"\n"
"            QListWidget::item{\n"
"                padding:1px;\n"
"                font-size: 14px;\n"
"                } \n"
"            QToolTip{\n"
"                font-size: 16px;\n"
"                padding: 15px;\n"
"                }\n"
"\n"
"QLineEdit, QPushButton{\n"
"    padding: 5;\n"
"    border: 1px solid rgb(39, 44, 54);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(39, 44, 54);\n"
"}\n"
"\n"
"QTreeView:disabled{\n"
"    color: rgb(60,60,60);\n"
"}\n"
"\n"
"QMenu::separator {\n"
"     height: 2px;\n"
"     margin: 2px 5px 2px 4px;\n"
"    background-color: red;\n"
"    color: red;\n"
" }\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_13.setContentsMargins(-1, -1, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.splitter = QtWidgets.QSplitter(self.frame_3)
        self.splitter.setStyleSheet("         \n"
"       \n"
"")
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_31 = QtWidgets.QFrame(self.splitter)
        self.frame_31.setStyleSheet("")
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_2.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ui_layout_tree = QtWidgets.QVBoxLayout()
        self.ui_layout_tree.setObjectName("ui_layout_tree")
        self.verticalLayout_2.addLayout(self.ui_layout_tree)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.ui_layout_group_box = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.ui_layout_group_box.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ui_layout_group_box.setContentsMargins(50, 0, 0, 0)
        self.ui_layout_group_box.setSpacing(0)
        self.ui_layout_group_box.setObjectName("ui_layout_group_box")
        self.verticalLayout_13.addWidget(self.splitter)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addWidget(self.frame_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.uiBtnEditNode.setText(_translate("Form", "Edit"))
        self.uiBtnCheckCoverage.setText(_translate("Form", "Check Coverage"))
        self.uiBtnCheckHtmlReport.setText(_translate("Form", "Check Report"))
        self.uiBtnUpdateRequirements.setText(_translate("Form", "Update All Requirements"))
        self.uiBtnNewModule.setText(_translate("Form", "New Module"))
        self.lab_requirements.setText(_translate("Form", "Requirements"))
        self.name_2.setText(_translate("Form", "Project Path:"))
        self.ui_lab_project_path.setText(_translate("Form", "?"))
        self.uiBtnSetProjectPath.setToolTip(_translate("Form", "Set Project Path"))
        self.name_5.setText(_translate("Form", "Total:"))
        self.ui_lab_req_total.setText(_translate("Form", "0"))
        self.name_4.setText(_translate("Form", "Covered:"))
        self.ui_lab_req_covered.setText(_translate("Form", "?"))
        self.name_3.setText(_translate("Form", "Not Covered:"))
        self.ui_lab_req_not_covered.setText(_translate("Form", "?"))
        self.lab_project_files.setText(_translate("Form", "Project Files"))
import files_rc
