# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_add_req_module.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(837, 288)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_global = QtWidgets.QFrame(Form)
        self.frame_global.setStyleSheet("\n"
"\n"
"QFrame, QPushButton, QLineEdit, QComboBox, QCheckBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton {    \n"
"    border: none;\n"
"    padding: 5;\n"
"    width: 60px;\n"
"    background-color: rgb(39, 44, 54);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit, QListWidget, QComboBox{\n"
"    padding: 5;\n"
"    background-color: rgb(39, 44, 54);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"}\n"
" QCheckBox{\n"
"    padding: 5;\n"
"\n"
"}\n"
"\n"
"\n"
"")
        self.frame_global.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_global.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_global.setObjectName("frame_global")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_global)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_heading = QtWidgets.QFrame(self.frame_global)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_heading.sizePolicy().hasHeightForWidth())
        self.frame_heading.setSizePolicy(sizePolicy)
        self.frame_heading.setStyleSheet("QFrame, QPushButton, QLineEdit{\n"
"    background-color: rgb(27, 29, 35);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QPushButton {    \n"
"    border: none;\n"
"    padding: 5;\n"
"    width: 50px;\n"
"    background-color: rgb(39, 44, 54);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {    \n"
"    background-color: rgb(85, 170, 255);\n"
"\n"
"}\n"
"\n"
"QLineEdit, QListWidget{\n"
"    padding: 5;\n"
"    background-color: rgb(39, 44, 54);\n"
"    border: 1px solid rgb(100, 100, 100);\n"
"}\n"
"\n"
"\n"
"")
        self.frame_heading.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_heading.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_heading.setObjectName("frame_heading")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_heading)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_heading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_top.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(44, 49, 60)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_logo = QtWidgets.QFrame(self.frame_top)
        self.frame_logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_logo.setObjectName("frame_logo")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_logo)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.logo = QtWidgets.QLabel(self.frame_logo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(30, 0))
        font = QtGui.QFont()
        font.setFamily("ZF Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgb(58, 89, 245);")
        self.logo.setObjectName("logo")
        self.horizontalLayout_6.addWidget(self.logo)
        self.horizontalLayout_3.addWidget(self.frame_logo)
        self.frame_caption = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_caption.sizePolicy().hasHeightForWidth())
        self.frame_caption.setSizePolicy(sizePolicy)
        self.frame_caption.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_caption.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_caption.setObjectName("frame_caption")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_caption)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_window_name = QtWidgets.QLabel(self.frame_caption)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_window_name.sizePolicy().hasHeightForWidth())
        self.label_window_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_window_name.setFont(font)
        self.label_window_name.setObjectName("label_window_name")
        self.horizontalLayout_4.addWidget(self.label_window_name)
        self.horizontalLayout_3.addWidget(self.frame_caption)
        self.frame_close = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_close.sizePolicy().hasHeightForWidth())
        self.frame_close.setSizePolicy(sizePolicy)
        self.frame_close.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_close.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_close.setObjectName("frame_close")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_close)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_close = QtWidgets.QPushButton(self.frame_close)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(20, 16777215))
        self.btn_close.setStyleSheet("")
        self.btn_close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_5.addWidget(self.btn_close)
        self.horizontalLayout_3.addWidget(self.frame_close, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.verticalLayout_5.addWidget(self.frame_heading)
        self.frame_content = QtWidgets.QFrame(self.frame_global)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_content.sizePolicy().hasHeightForWidth())
        self.frame_content.setSizePolicy(sizePolicy)
        self.frame_content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_doors = QtWidgets.QFrame(self.frame_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_doors.sizePolicy().hasHeightForWidth())
        self.frame_doors.setSizePolicy(sizePolicy)
        self.frame_doors.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_doors.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_doors.setObjectName("frame_doors")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_doors)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_16 = QtWidgets.QFrame(self.frame_doors)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.frame_16)
        self.label_16.setMinimumSize(QtCore.QSize(120, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_18.addWidget(self.label_16)
        self.ui_le_module_path = QtWidgets.QLineEdit(self.frame_16)
        self.ui_le_module_path.setObjectName("ui_le_module_path")
        self.horizontalLayout_18.addWidget(self.ui_le_module_path)
        self.verticalLayout_3.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_doors)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.frame_17)
        self.label_17.setMinimumSize(QtCore.QSize(120, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.ui_le_module_columns = QtWidgets.QLineEdit(self.frame_17)
        self.ui_le_module_columns.setObjectName("ui_le_module_columns")
        self.horizontalLayout_19.addWidget(self.ui_le_module_columns)
        self.verticalLayout_3.addWidget(self.frame_17)
        self.frame_20 = QtWidgets.QFrame(self.frame_doors)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.ui_cb_check_coverage = QtWidgets.QCheckBox(self.frame_20)
        self.ui_cb_check_coverage.setObjectName("ui_cb_check_coverage")
        self.horizontalLayout_23.addWidget(self.ui_cb_check_coverage)
        self.verticalLayout_3.addWidget(self.frame_20, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.frame_doors)
        self.verticalLayout_5.addWidget(self.frame_content)
        self.frame_bottom_buttons_2 = QtWidgets.QFrame(self.frame_global)
        self.frame_bottom_buttons_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bottom_buttons_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bottom_buttons_2.setObjectName("frame_bottom_buttons_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_bottom_buttons_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ui_btn_cancel = QtWidgets.QPushButton(self.frame_bottom_buttons_2)
        self.ui_btn_cancel.setObjectName("ui_btn_cancel")
        self.horizontalLayout_12.addWidget(self.ui_btn_cancel)
        self.ui_btn_ok = QtWidgets.QPushButton(self.frame_bottom_buttons_2)
        self.ui_btn_ok.setObjectName("ui_btn_ok")
        self.horizontalLayout_12.addWidget(self.ui_btn_ok)
        self.verticalLayout_5.addWidget(self.frame_bottom_buttons_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_global)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Create Project"))
        self.logo.setText(_translate("Form", "R2"))
        self.label_window_name.setText(_translate("Form", "Add module"))
        self.btn_close.setToolTip(_translate("Form", "Close"))
        self.label_16.setText(_translate("Form", "Module:"))
        self.label_17.setText(_translate("Form", "Columns:"))
        self.ui_cb_check_coverage.setText(_translate("Form", "Check Coverage"))
        self.ui_btn_cancel.setText(_translate("Form", "Cancel"))
        self.ui_btn_ok.setText(_translate("Form", "OK"))
import files_rc
